# Numpy: Assignment

## Load library

In [1]:
import numpy as np

## Create Two numpy arrays with list, arange and array

In [2]:
list_1 = [[1,2,5],[3,4,6]]
narray_1 = np.array(list_1)
narray_2 = np.arange(7,13).reshape(2,3)
narray_3 = np.array([[1,2],[3,4],[5,6]])
narray_1, narray_2, narray_3

(array([[1, 2, 5],
        [3, 4, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]]), array([[1, 2],
        [3, 4],
        [5, 6]]))

## 1.Find minimum in np array

In [3]:
min_of_narray_1 = narray_1.min()
min_of_narray_1_row = narray_1.min(axis=1)
min_of_narray_1_col = narray_1.min(axis=0)
min_of_narray_1, min_of_narray_1_row, min_of_narray_1_col

(1, array([1, 3]), array([1, 2, 5]))

## 2.Find maximum in np array

In [4]:
max_of_narray_1 = narray_1.max()
max_of_narray_1_row = narray_1.max(axis=1)
max_of_narray_1_col = narray_1.max(axis=0)
max_of_narray_1, max_of_narray_1_row, max_of_narray_1_col

(6, array([5, 6]), array([3, 4, 6]))

## 3.Mean

In [5]:
mean_of_narray_1 = narray_1.mean()
mean_of_narray_1_row = narray_1.mean(axis=1)
mean_of_narray_1_col = narray_1.mean(axis=0)
mean_of_narray_1, mean_of_narray_1_row, mean_of_narray_1_col

(3.5, array([ 2.66666667,  4.33333333]), array([ 2. ,  3. ,  5.5]))

## 4.Argmin: Index of min value

In [6]:
argmin_of_narray_1 = np.argmin(narray_1)
argmin_of_narray_1_row = np.argmin(narray_1, axis=1)
argmin_of_narray_1_col = np.argmin(narray_1, axis=0)
argmin_of_narray_1, argmin_of_narray_1_row, argmin_of_narray_1_col

(0, array([0, 0]), array([0, 0, 0]))

## 5.Argmax: Index of max value

In [7]:
argmax_of_narray_1 = np.argmax(narray_1)
argmax_of_narray_1_row = np.argmax(narray_1, axis=1)
argmax_of_narray_1_col = np.argmax(narray_1, axis=0)
argmax_of_narray_1, argmax_of_narray_1_row, argmax_of_narray_1_col

(5, array([2, 2]), array([1, 1, 1]))

## 6.Linalg: Solve linear equations

In [19]:
#AX = b
A = np.array([[5,4,3], [1,3,2], [7,2,8]])
B = np.array([5,6,4])
X = np.linalg.solve(A, B)
X

array([-0.89552239,  1.73134328,  0.85074627])

## 7.Flat or 1-d array

In [9]:
flat_narray_1 = narray_1.flatten()
flat_narray_1

array([1, 2, 5, 3, 4, 6])

## 8.Ravel

In [23]:
row_wise_flat = np.ravel(narray_1, order='C')
col_wise_flat = np.ravel(narray_1, order='F')
a_wise_flat = np.ravel(narray_1, order='A')
mem_wise_flat = np.ravel(narray_1, order='K')
row_wise_flat, col_wise_flat, a_wise_flat, mem_wise_flat

(array([1, 2, 5, 3, 4, 6]),
 array([1, 3, 2, 4, 5, 6]),
 array([1, 2, 5, 3, 4, 6]),
 array([1, 2, 5, 3, 4, 6]))

## 9.Dot or Matrix product

In [10]:
dot_narray13 = narray_1.dot(narray_3)
dot_narray23 = np.dot(narray_2,narray_3)
dot_narray13, dot_narray23

(array([[32, 40],
        [45, 58]]), array([[ 76, 100],
        [103, 136]]))

## 10.Element-wise Multiplication

In [11]:
element_mulp12 = narray_1 * narray_2
element_mulp12

array([[ 7, 16, 45],
       [30, 44, 72]])

## 11.Arange and Reshape

In [12]:
arange_array = np.arange(7,13,0.5)
reshape_array = arange_array.reshape(3,-1)
arange_array, reshape_array

(array([  7. ,   7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5,  11. ,
         11.5,  12. ,  12.5]), array([[  7. ,   7.5,   8. ,   8.5],
        [  9. ,   9.5,  10. ,  10.5],
        [ 11. ,  11.5,  12. ,  12.5]]))

## 12.Identity/Eye

In [13]:
eye_array = np.eye(3,3)
eye_array

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## 13.Sum

In [14]:
sum_of_narray_1 = narray_1.sum()
sum_of_narray_1_row = narray_1.sum(axis=1)
sum_of_narray_1_col = narray_1.sum(axis=0)
element_sum_narray12 = narray_1 + narray_2
sum_of_narray_1, sum_of_narray_1_row, sum_of_narray_1_col, element_sum_narray12

(21, array([ 8, 13]), array([ 4,  6, 11]), array([[ 8, 10, 14],
        [13, 15, 18]]))

## 14.Diagonal

In [15]:
diag_narray1_col0 = np.diag(narray_1, k=0)
diag_narray1_col1 = np.diag(narray_1, k=1)
diag_narray1_col2 = np.diag(narray_1, k=2)
diag_narray1_col_last = np.diag(narray_1, k=-1)
diag_narray1_col0, diag_narray1_col1, diag_narray1_col2, diag_narray1_col_last

(array([1, 4]), array([2, 6]), array([5]), array([3]))

## 15.Tril: Lower triangle

In [16]:
tril_narray1_diag0 = np.tril(narray_1, k=0)
tril_narray1_diag1 = np.tril(narray_1, k=1)
tril_narray1_diag2 = np.tril(narray_1, k=2)
tril_narray1_diag_last = np.tril(narray_1, k=-1)
tril_narray1_diag0, tril_narray1_diag1, tril_narray1_diag2, tril_narray1_diag_last

(array([[1, 0, 0],
        [3, 4, 0]]), array([[1, 2, 0],
        [3, 4, 6]]), array([[1, 2, 5],
        [3, 4, 6]]), array([[0, 0, 0],
        [3, 0, 0]]))

## 16.Triu: Upper triangle

In [17]:
triu_narray1_diag0 = np.triu(narray_1, k=0)
triu_narray1_diag1 = np.triu(narray_1, k=1)
triu_narray1_diag2 = np.triu(narray_1, k=2)
triu_narray1_diag_last = np.triu(narray_1, k=-1)
triu_narray1_diag0, triu_narray1_diag1, triu_narray1_diag2, triu_narray1_diag_last

(array([[1, 2, 5],
        [0, 4, 6]]), array([[0, 2, 5],
        [0, 0, 6]]), array([[0, 0, 5],
        [0, 0, 0]]), array([[1, 2, 5],
        [3, 4, 6]]))