# numpy-assignement-2(own-implementation)

## Import Libraries

In [2]:
import numpy as np


## Create arrays

In [3]:
narray_1 = np.array([[1,2],[3,4]])
narray_2 = np.array([[5,6],[7,8]])
array_size = narray_1.size
r,c = narray_1.shape

## find min_element,max_element,min_index,max_index

In [17]:
min_element = narray_1[0,0]
max_element = narray_1[0,0]
min_index = 0
max_index = 0
counter = 0
for i in range(0,r):
    for j in range(0,c):
        if narray_1[i,j] <  min_element:
            min_element = narray_1[i,j]
            min_index = counter
            counter+=1
        elif narray_1[i,j] > max_element:
            max_element = narray_1[i,j]
            max_index = counter
            counter+=1
        else:
            counter+=1
min_element, max_element, min_index, max_index

(1, 4, 0, 3)

## find min_element,max_element,min_index,max_index along row

In [10]:
row_min_element = [0] * r
row_max_element = [0] * r
row_min_index = [0] * r
row_max_index = [0] * r
row_counter = 0
for i in range(0,r):
    row_min_element[i] = narray_1[i,0]
    row_max_element[i] = narray_1[i,0]
    for j in range(0,c):
        if narray_1[i,j] <=  row_min_element[i]:
            row_min_element[i] = narray_1[i,j]
            row_min_index[i] = j
        elif narray_1[i,j] > row_max_element[i]:
            row_max_element[i] = narray_1[i,j]
            row_max_index[i] = j
    
            
row_min_element, row_max_element, row_min_index, row_max_index

([1, 3], [2, 4], [0, 0], [1, 1])

## find min_element,max_element,min_index,max_index along column

In [11]:
col_min_element = [0] * c
col_max_element = [0] * c
col_min_index = [0] * c
col_max_index = [0] * c 
col_counter = 0
for j in range(0,c):
    col_min_element[j] = narray_1[0,j]
    col_max_element[j] = narray_1[0,j]
    for i in range(0,r):
        if narray_1[i,j] <=  col_min_element[i]:
            col_min_element[j] = narray_1[i,j]
            col_min_index[j] = i
        elif narray_1[i,j] > col_max_element[i]:
            col_max_element[j] = narray_1[i,j]
            col_max_index[j] = i

            
            
col_min_element, col_max_element, col_min_index, col_max_index

([1, 2], [3, 4], [0, 0], [1, 1])

## Mean and Sum of elements and flatten

In [30]:
mean = 0
sum_of_elements = 0
list_1 = []
for i in range(0,r):
    for j in range(0,c):
        sum_of_elements+= narray_1[i,j]
        list_1.append(narray_1[i,j])
mean = sum_of_elements / array_size
sum_of_elements, mean, list_1
        

(10, 2.5, [1, 2, 3, 4])

## Mean and Sum of elements along row

In [36]:
row_mean = []
row_sum_list = []
for i in range(0,r):
    row_sum = 0
    for j in range(0,c):
        row_sum+=narray_1[i,j]
    row_sum_list.append(row_sum)
    row_mean.append(row_sum / c)
row_sum_list, row_mean    

([3, 7], [1.5, 3.5])

## Mean, Sum of elements  and flatten along col

In [38]:
col_mean = []
col_list = []
col_sum_list = []
for j in range(0,c):
    col_sum = 0
    for i in range(0,r):
        col_sum+=narray_1[i,j]
        col_list.append(narray_1[i,j])
    col_sum_list.append(col_sum)
    col_mean.append(col_sum / r)
col_sum_list, col_mean, col_list    

([4, 6], [2.0, 3.0], [1, 3, 2, 4])

## Element-wise product

In [7]:
element_product_array = np.empty((2,2))
for i in range(0,r):
    for j in range(0,c):
        element_product_array[i,j] = narray_1[i,j] * narray_2[i,j]
element_product_array       

array([[  5.,  12.],
       [ 21.,  32.]])

## Dot or Matrix product

In [7]:
r1, c1 = narray_1.shape
r2, c2 = narray_2.shape
dot_product_array = np.empty((r1,c2))

for i in range(0,r1):
    for k in range(0,c1):
        sum=0
        for j in range(0,c2):
            sum+=narray_1[i,j] * narray_2[j,k]
        dot_product_array[i,k] = sum
dot_product_array           

array([[ 19.,  22.],
       [ 43.,  50.]])

## Reshape array

In [6]:

reshape_r = 1
reshape_c = 4
reshape_array = np.zeros((reshape_r, reshape_c))
k = 0
l = 0
while((k<reshape_r) & (l<reshape_c)):
    for i in range(0,r):
        for j in range(0,c):
            reshape_array[k,l] = narray_1[i,j]
            #print(reshape_array)
            if (l<reshape_c-1):
                l+=1
            else:
                l=0
                if(k<reshape_r):
                    k+=1
reshape_array        

array([[ 1.,  2.,  3.,  4.]])

## diag

In [10]:

diag_array = np.empty((2,2))
for i in range(0,r):
    for j in range(0,c):
        if i == j:
            diag_array[i,j] = narray_1[i,j]           
diag_array       

array([[ 1.,  0.],
       [ 0.,  4.]])

## tril

In [11]:
#tril
tril_array = np.empty((2,2))
for i in range(0,r):
    for j in range(0,c):
        if i <= j:
            tril_array[i,j] = narray_1[i,j]           
tril_array       

array([[ 1.,  2.],
       [ 0.,  4.]])

## triu

In [12]:
#triu
triu_array = np.empty((2,2))
for i in range(0,r):
    for j in range(0,c):
        if i >= j:
            triu_array[i,j] = narray_1[i,j]           
triu_array  

array([[ 1.,  0.],
       [ 3.,  4.]])